### ISSUE TITLE
Editing of files disabled. Only viewing

### ISSUE THREAD

**Issue by nikosfrangakis** [ONLYOFFICE/onlyoffice-redmine#12]
I am not able to edit files anymore with onlyoffice within redmine.
The tool bar is missing and i can only view the document.

OS: debian 11, with latest updates
Environment:
  Redmine version                4.2.3.stable.21244
  Ruby version                   2.7.2-p137 (2020-10-01) [x86_64-linux]
  Rails version                  5.2.6
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.14.1
  Git                            2.34.1
  Filesystem                     
Redmine plugins:
  onlyoffice_redmine             1.1.0
  redmine_ckeditor               1.2.3
  redmine_dmsf                   2.4.9

**Comment by LinneyS** [comment]
Could you please specify if the problem recurs or we can close the topic?
