### ISSUE TITLE
can't edit when chossing and swiching font

### ISSUE THREAD

**Issue by wangwuqi** [ONLYOFFICE/onlyoffice-redmine#139]
when i open a ducument with onlyoffice in redmine, i can edit as follows
![image](https://github.com/ONLYOFFICE/onlyoffice-redmine/assets/22237278/73851316-bdf1-4597-b980-c10c0f0491d6)
but when i click the fonts selection, it show a warning as follows
![image](https://github.com/ONLYOFFICE/onlyoffice-redmine/assets/22237278/26daa99d-d717-42dd-ac8a-12234d07280e)
after i close or click "确定"，the editor is locked and i can't edit the file anymore
![image](https://github.com/ONLYOFFICE/onlyoffice-redmine/assets/22237278/16abeb61-ac46-4325-a488-9a0cec2b3395)

**Comment by rsnegirev** [comment]
Hi @wangwuqi 

Can you please send an archive with the fonts used?

**Comment by wangwuqi** [comment]
i use the mini_fonts from https://github.com/funggtopp/onlyoffice-chinese-fonts

**Comment by rsnegirev** [comment]
So, you're using fonts from this repo https://github.com/funggtopp/onlyoffice-chinese-fonts/tree/master/mini_fonts

or from whole branch https://github.com/funggtopp/onlyoffice-chinese-fonts ?

**Comment by wangwuqi** [comment]
i cloned the repository，then copied the mini_fonts folder to onlyoffice and installed these fonts，it works well in test example page，while having bug in redmine shown as above

**Comment by rsnegirev** [comment]
And the whole scenario is to enter some text and open a drop-down list with fonts?

**Comment by wangwuqi** [comment]
yes

**Comment by wangwuqi** [comment]
my onlyoffice and redmine versions are as follows
![image](https://github.com/ONLYOFFICE/onlyoffice-redmine/assets/22237278/078e3023-21a6-4775-ba0e-afbba99d9355)
![onlyoffice-fonts](https://github.com/ONLYOFFICE/onlyoffice-redmine/assets/22237278/ffba8b3d-3faf-4bc0-8350-6ee11c48bd47)
![redmine-version](https://github.com/ONLYOFFICE/onlyoffice-redmine/assets/22237278/18092931-f90d-41ae-a698-f794794f2a5f)

**Comment by avdddd1111** [comment]
Hello @wangwuqi  Have you closed the issue? Did the problem go away? If yes, how did you resolve it? As of today, a new version of the OnlyOffice plugin has been released (3.0.1). Have you tried installing it? Did the issue not reproduce there?
