### ISSUE TITLE
Plugin Installation problems

### ISSUE THREAD

**Issue by silasalbuquerque** [ONLYOFFICE/onlyoffice-redmine#27]
Hello fellows,

Some errors I found while installing the onlyoffice-redmine v1.1.0 plugin:

- [ E 2022-04-28 19:39:41.5432 909/Th age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /opt/redmine: The application encountered the following error: expected file /opt/redmine/plugins/onlyoffice_redmine/app/models/file_uitility.rb to define constant FileUitility, but didn't (Zeitwerk::NameError);

- [ E 2022-04-28 19:55:15.5457 909/Tm age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /opt/redmine: The application encountered the following error: expected file /opt/redmine/plugins/onlyoffice_redmine/app/models/jwt_helper.rb to define constant JwtHelper, but didn't (Zeitwerk::NameError).

Wouldn't it be correct for the file "file_uitility.rb" to be called "file_utility.rb" and the constants (Class) FileUitility and JwtHelper to be called FileUtility and JWTHelper, respectively?

Why, when installing, are constants FileUitility and JwtHelper expected, instead of FileUtility and JWTHelper?

Redmine Environment:
  Ubuntu server 22.04
  Apache 2.4.52
  Redmine  5.0.0. stable
  Ruby  3.0.2-p107 (2021-07-07) [x86_64-linux-gnu]
  Rails  6.1.4.7
  Mysql 8.0.28-0ubuntu4

Redmine plugins:
  onlyoffice_redmine 1.1.0

Only Office Environment:
  Ubuntu server 22.04
  Nginx 1.18.0 (Ubuntu)

**Comment by pgutierrezn2** [comment]
Exact same errors here on:
Centos 8 
Redmine 5.0.2 stable 
Apache 2.4.37
ruby 2.7.2p137
Rails 6.1.6
mysql  Ver 8.0.26 
onlyoffice_redmine 1.1.0

Additionally this error has been reported [elsewhere](https://github.com/jgraichen/redmine_dashboard/issues/244#issue-1258350949)
