### ISSUE TITLE
Couldn't make it work with Redmine versions: 4.0.0, 4.1.5, 4.2.7 and 5.0.2

### ISSUE THREAD

**Issue by pgutierrezn2** [ONLYOFFICE/onlyoffice-redmine#32]
Basic Configuration:

- Centos 8
- mysql Ver 8.0.26
- onlyoffice_redmine plugin 1.1.0
- onlyoffice: onlyoffice/documentserver:latest [2022/07/06]

Initially I tried installing the plugin in Redmine 5.0.2 without success facing #27 issue everytime. I tried both a docker based and a manual installation. But the same issue appeared.
Then I read issue #30  warning that may be the plugin was not compatible with Redmine version 5.x although the documentation says otherwise. And so, I tried Redmine versions 4.0.0, 4.1.5 and 4.2.7 This time the error was different. Everytime I tried to add a new onlyoffice document from Redmine "Documents" tab I saw this error:

> App 194 output: I, [2022-07-06T06:38:18.482800 #194]  INFO -- :   Current user: admin (id=1)
App 194 output: I, [2022-07-06T06:38:18.487409 #194]  INFO -- : Completed 500 Internal Server Error in 9ms (ActiveRecord: 2.7ms)
App 194 output: F, [2022-07-06T06:38:18.487813 #194] FATAL -- :
App 194 output: F, [2022-07-06T06:38:18.487868 #194] FATAL -- : Errno::ENOENT (No such file or directory @ rb_sysopen - /usr/src/redmine/plugins/onlyoffice_redmine/assets/document-templates/en-US/new.docx):
App 194 output: F, [2022-07-06T06:38:18.487884 #194] FATAL -- :
App 194 output: F, [2022-07-06T06:38:18.487895 #194] FATAL -- : plugins/onlyoffice_redmine/app/controllers/onlyoffice_create_controller.rb:44:in `read'
App 194 output: plugins/onlyoffice_redmine/app/controllers/onlyoffice_create_controller.rb:44:in `create_attachment_from_template_file'
App 194 output: plugins/onlyoffice_redmine/app/controllers/onlyoffice_create_controller.rb:17:in `create'
App 194 output: lib/redmine/sudo_mode.rb:63:in `sudo_mode'

The missing file mentioned: `/usr/src/redmine/plugins/onlyoffice_redmine/assets/document-templates/en-US/new.doc` was, indeed, missing but couldn't figure out the reason for that.

**Comment by Eloncase** [comment]
Hello!
Issue with version 5 will be fixed soon you can check the progress in #27 

As for file creation, when you did a manual installation, have you pulled submodules?
`git submodule update --init --recursive`
This might be the reason why you don't have the document templates.

**Comment by rooneysh** [comment]
I cloned a develop branch which include modification of 'JwtHelper' and install it on my redmine docker today.
But still the docker can't startup.

=> Booting Puma
=> Rails 6.1.6 application starting in production 
=> Run `bin/rails server --help` for more startup options
W, [2022-07-19T02:43:24.646663 #1]  WARN -- : Creating scope :sorted. Overwriting existing method User.sorted.
W, [2022-07-19T02:43:24.682775 #1]  WARN -- : Creating scope :system. Overwriting existing method Enumeration.system.
Exiting
/usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/callbacks.rb:25:in `on_file_autoloaded': expected file /usr/src/redmine/plugins/onlyoffice_redmine/app/models/format_uitility.rb to define constant FormatUitility, but didn't (Zeitwerk::NameError)
      raise Zeitwerk::NameError.new("expected file #{file} to define constant #{cpath}, but didn't", cref.last)
      ^^^^^
        from /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:28:in `require'
        from /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:127:in `const_get'
        from /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:127:in `cget'
        from /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:239:in `block (2 levels) in eager_load'
        from /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:41:in `block in ls'
        from /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:27:in `each'
        from /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/loader/helpers.rb:27:in `ls'
        from /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:234:in `block in eager_load'
        from /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:219:in `synchronize'
        from /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:219:in `eager_load'
        from /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:318:in `each'
        from /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/loader.rb:318:in `eager_load_all'
        from /usr/local/bundle/gems/railties-6.1.6/lib/rails/application/finisher.rb:133:in `block in <module:Finisher>'
        from /usr/local/bundle/gems/railties-6.1.6/lib/rails/initializable.rb:32:in `instance_exec'
        from /usr/local/bundle/gems/railties-6.1.6/lib/rails/initializable.rb:32:in `run'
        from /usr/local/bundle/gems/railties-6.1.6/lib/rails/initializable.rb:61:in `block in run_initializers'
        from /usr/local/lib/ruby/3.1.0/tsort.rb:228:in `block in tsort_each'
        from /usr/local/lib/ruby/3.1.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
        from /usr/local/lib/ruby/3.1.0/tsort.rb:431:in `each_strongly_connected_component_from'
        from /usr/local/lib/ruby/3.1.0/tsort.rb:349:in `block in each_strongly_connected_component'
        from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each'
        from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `call'
        from /usr/local/lib/ruby/3.1.0/tsort.rb:347:in `each_strongly_connected_component'
        from /usr/local/lib/ruby/3.1.0/tsort.rb:226:in `tsort_each'
        from /usr/local/lib/ruby/3.1.0/tsort.rb:205:in `tsort_each'
        from /usr/local/bundle/gems/railties-6.1.6/lib/rails/initializable.rb:60:in `run_initializers'
        from /usr/local/bundle/gems/railties-6.1.6/lib/rails/application.rb:391:in `initialize!'
        from /usr/src/redmine/config/environment.rb:16:in `<top (required)>'
        from /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
        from /usr/local/bundle/gems/zeitwerk-2.6.0/lib/zeitwerk/kernel.rb:35:in `require'
        from /usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:332:in `block in require'
        from /usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:299:in `load_dependency'
        from /usr/local/bundle/gems/activesupport-6.1.6/lib/active_support/dependencies.rb:332:in `require'
        from config.ru:3:in `block in <main>'
        from /usr/local/bundle/gems/rack-2.2.4/lib/rack/builder.rb:116:in `eval'
        from /usr/local/bundle/gems/rack-2.2.4/lib/rack/builder.rb:116:in `new_from_string'
        from /usr/local/bundle/gems/rack-2.2.4/lib/rack/builder.rb:105:in `load_file'
        from /usr/local/bundle/gems/rack-2.2.4/lib/rack/builder.rb:66:in `parse_file'
        from /usr/local/bundle/gems/rack-2.2.4/lib/rack/server.rb:349:in `build_app_and_options_from_config'
        from /usr/local/bundle/gems/rack-2.2.4/lib/rack/server.rb:249:in `app'
        from /usr/local/bundle/gems/rack-2.2.4/lib/rack/server.rb:422:in `wrapped_app'
        from /usr/local/bundle/gems/rack-2.2.4/lib/rack/server.rb:312:in `block in start'
        from /usr/local/bundle/gems/rack-2.2.4/lib/rack/server.rb:379:in `handle_profiling'
        from /usr/local/bundle/gems/rack-2.2.4/lib/rack/server.rb:311:in `start'
        from /usr/local/bundle/gems/railties-6.1.6/lib/rails/commands/server/server_command.rb:39:in `start'
        from /usr/local/bundle/gems/railties-6.1.6/lib/rails/commands/server/server_command.rb:144:in `block in perform'
        from <internal:kernel>:90:in `tap'
        from /usr/local/bundle/gems/railties-6.1.6/lib/rails/commands/server/server_command.rb:135:in `perform'
        from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from /usr/local/bundle/gems/railties-6.1.6/lib/rails/command/base.rb:69:in `perform'
        from /usr/local/bundle/gems/railties-6.1.6/lib/rails/command.rb:48:in `invoke'
        from /usr/local/bundle/gems/railties-6.1.6/lib/rails/commands.rb:18:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
