### ISSUE TITLE
Installation ob redmine 5.0 is not possible

### ISSUE THREAD

**Issue by auc-mma** [ONLYOFFICE/onlyoffice-redmine#35]
i use Redmine in a docker-container..
After coping your files to the plugin folder ...i get these errors in log file

Installing gems required by plugins...

You are replacing the current local value of without, which is currently "development:test"
fatal: not a git repository (or any of the parent directories): .git
Migrating plugins. Please be patient, this could take a while...
fatal: not a git repository (or any of the parent directories): .git

do you have any idea about the reason?

thank you!

**Comment by Eloncase** [comment]
will be fixed in 2.0 release
