### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by 1stdevfriend** [ONLYOFFICE/onlyoffice-redmine#45]
I tried installing onlyoffice_redmine. Rake build was successful. However on restart passenger is showing this under logs.

[ E 2023-01-17 06:45:06.7469 152/T4a age/Cor/App/Implementation.cpp:221 ]: Could not spawn process for application /opt/bitnami/redmine: The application encountered the following error: /opt/bitnami/redmine/plugins/onlyoffice_redmine/app/controllers/onlyoffice_controller.rb:248: syntax error, unexpected .., expecting ']'
... title = attachment.filename[..attachment.disk_filename.inde...
/opt/bitnami/redmine/plugins/onlyoffice_redmine/app/controllers/onlyoffice_controller.rb:248: syntax error, unexpected ']', expecting end
...hment.disk_filename.index(".")] + 'docx'
(SyntaxError)
Error ID: b1655414

A helping hand or just info will do for me :)

**Comment by Eloncase** [comment]
Hello @1stdevfriend.
Which branch you were trying to build? And which Ruby version are you using?

Just tried running from `develop` and `main` branches. Works fine for me.

I'm using official docker image tho, not the bitnami one. That might be a problem too.

**Comment by 1stdevfriend** [comment]
@Eloncase 
I'm using bitnami one. I believe that's exactly the problem.

**Comment by LinneyS** [comment]
Could you please specify if the problem recurs or we can close the topic?

**Comment by 1stdevfriend** [comment]
Not fixed yet. I'll be looking into it again.

**Comment by avdddd1111** [comment]
Hello @1stdevfriend!, sorry for the delayed response! I checked in Bitnami Docker (5.0.6) and VM (5.1.1). I didn't encounter any issues. A new version of the OnlyOffice plugin has been released (3.0.1). Please try installing it! Will the problem be reproduced in the new version?

**Comment by 1stdevfriend** [comment]
No. I am very skeptical of the newer version to fail at all. 

My bitnami redmine was set on 4.2.3 and that's something that might be creating the issue. If I can get a way to update the container. I'll check it up. 

Please close this issue <3

**Comment by Rita-Bubnova** [comment]
I close this issue. Feel free to comment or reopen it if you got further questions.
