### ISSUE TITLE
Download file error when open file in redmine

### ISSUE THREAD

**Issue by z7924723** [ONLYOFFICE/onlyoffice-redmine#47]
Hi all, 
I success added Onlyoffice plugin into Redmine, but when I open a file by using Onlyoffice, I get the error message like this
`nodeJS - error downloadFile:url=http://localhost:7500//onlyoffice/download/1?key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdHRhY2htZW50X2lkIjoxLCJ0eXBlIjoiZG93bmxvYWQiLCJ1c2VyaWQiOjF9.C-cUqq8rPMP0L2ay6HWcyBXH2mzpan_c6p8fBg4DgIs;attempt=2;code:ECONNREFUSED;connect:undefined Error: connect ECONNREFUSED 127.0.0.1:7500`

I realize the error is due to two forward slashes after the port number(success download by using the above URL after deleting one slash), but I check the setting about "Server address for internal requests from ONLYOFFICE Docs" and it doesn't have any slash after the port number.

Here is my setting
![image](https://user-images.githubusercontent.com/33885494/224669939-441a21d4-f98b-4147-949b-286f9c7f59e7.png)

I using docker-compose to deploy Redmine and OnlyOffice, here is the environment:
1. onlyoffice/documentserver:7.3.2
2. redmine:5.0.4-bullseye
3. onlyoffice redmine plugin: tag 2.0.0
4. mariadb:10.7.1-focal

**Comment by SergeyKorneyev** [comment]
Hello,
Please try using the server's IP address instead of **localhost** in the settings and check if the issue persists.

**Comment by z7924723** [comment]
It works!!!
Thanks very much.
